/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    buyers: BuyerAuthOperations;
  };
  blocks: {};
  collections: {
    vehicles: Vehicle;
    dealers: Dealer;
    leads: Lead;
    branches: Branch;
    media: Media;
    users: User;
    buyers: Buyer;
    plans: Plan;
    makes: Make;
    models: Model;
    variants: Variant;
    'body-types': BodyType;
    'fuel-types': FuelType;
    transmissions: Transmission;
    drivetrains: Drivetrain;
    colours: Colour;
    'feature-categories': FeatureCategory;
    features: Feature;
    provinces: Province;
    cities: City;
    franchises: Franchise;
    'dealer-groups': DealerGroup;
    accreditations: Accreditation;
    'consent-records': ConsentRecord;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    buyers: BuyersSelect<false> | BuyersSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    makes: MakesSelect<false> | MakesSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    'body-types': BodyTypesSelect<false> | BodyTypesSelect<true>;
    'fuel-types': FuelTypesSelect<false> | FuelTypesSelect<true>;
    transmissions: TransmissionsSelect<false> | TransmissionsSelect<true>;
    drivetrains: DrivetrainsSelect<false> | DrivetrainsSelect<true>;
    colours: ColoursSelect<false> | ColoursSelect<true>;
    'feature-categories': FeatureCategoriesSelect<false> | FeatureCategoriesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    franchises: FranchisesSelect<false> | FranchisesSelect<true>;
    'dealer-groups': DealerGroupsSelect<false> | DealerGroupsSelect<true>;
    accreditations: AccreditationsSelect<false> | AccreditationsSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'finance-defaults': FinanceDefault;
  };
  globalsSelect: {
    'finance-defaults': FinanceDefaultsSelect<false> | FinanceDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Buyer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface BuyerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  title?: string | null;
  condition: 'new' | 'demo' | 'pre_owned';
  make: number | Make;
  model: number | Model;
  variant?: (number | null) | Variant;
  /**
   * Only if the variant does not cover it, for example a trim pack.
   */
  derivative?: string | null;
  modelYear: number;
  registrationYear?: number | null;
  mileageKm: number;
  bodyType?: (number | null) | BodyType;
  fuelType?: (number | null) | FuelType;
  transmission?: (number | null) | Transmission;
  drivetrain?: (number | null) | Drivetrain;
  exteriorColour?: (number | null) | Colour;
  interiorColour?: (number | null) | Colour;
  /**
   * Pick from the list so buyers can filter by them.
   */
  features?: (number | Feature)[] | null;
  /**
   * Shown on the listing page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  engineCapacityCc?: number | null;
  cylinders?: number | null;
  powerKw?: number | null;
  torqueNm?: number | null;
  doors?: number | null;
  seats?: number | null;
  /**
   * Whole rands, for example 249900.
   */
  price: number;
  priceType: 'retail' | 'on_the_road' | 'poa';
  vatStatus?: ('vat_inclusive' | 'vat_exclusive' | 'non_vat') | null;
  /**
   * Set automatically when you change the price. Shows a price-drop badge when higher.
   */
  previousPrice?: number | null;
  priceHistory?:
    | {
        price?: number | null;
        changedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  monthlyEstimate?: number | null;
  /**
   * The first photo is the main one. Drag, or use Move up and Move down in the row menu.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Leave empty to use the photo's own description.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  video?: {
    /**
     * A YouTube or Vimeo link.
     */
    url?: string | null;
    provider?: ('youtube' | 'vimeo') | null;
  };
  /**
   * The dealership's own reference.
   */
  stockNumber?: string | null;
  /**
   * Never shown on the site or to other dealerships.
   */
  vin?: string | null;
  serviceHistory?: ('full_franchise' | 'full_independent' | 'partial' | 'none' | 'unknown') | null;
  roadworthy?: ('current' | 'expired' | 'not_required' | 'unknown') | null;
  licenceExpiry?: string | null;
  warrantyRemaining?: {
    months?: number | null;
    km?: number | null;
    provider?: string | null;
  };
  /**
   * Only Live cars, and Sold cars for 90 days, can be seen on the site.
   */
  status: 'draft' | 'pending_review' | 'live' | 'reserved' | 'sold' | 'expired' | 'archived';
  /**
   * The dealership selling this car.
   */
  dealer: number | Dealer;
  /**
   * Where the car is parked.
   */
  branch?: (number | null) | Branch;
  /**
   * Made-up stock for showing the site. Labelled as an example wherever it appears.
   */
  isDemonstration?: boolean | null;
  /**
   * Part of the web address. Set automatically.
   */
  publicRef?: string | null;
  publishedAt?: string | null;
  soldAt?: string | null;
  viewCount?: number | null;
  leadCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Car brands. Each make gets its own page on the site, so a few names that clash with other pages cannot be used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes".
 */
export interface Make {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Not used on the site yet.
   */
  isPopular?: boolean | null;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Make;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every photo needs a short description, so people using screen readers know what it shows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Needed unless Decorative only is ticked. Say what it shows, for example 2023 Toyota Hilux Raider, front view.
   */
  alt?: string | null;
  /**
   * Tick only for backgrounds and patterns.
   */
  isDecorative?: boolean | null;
  credit?: string | null;
  /**
   * A photo of the model, not of a real car for sale.
   */
  isDemonstration?: boolean | null;
  /**
   * Whose photo this is. Empty means it is Rynet's own.
   */
  dealer?: (number | null) | Dealer;
  /**
   * For example stock, dealers or agency.
   */
  folder?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  /**
   * Only verified dealerships can put cars live.
   */
  verificationStatus: 'pending' | 'verified' | 'suspended' | 'archived';
  /**
   * Not a real business. Labelled as an example on the site.
   */
  isDemonstration?: boolean | null;
  tradingName: string;
  /**
   * As registered with CIPC.
   */
  legalName: string;
  logo?: (number | null) | Media;
  aboutRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  foundedYear?: number | null;
  group?: (number | null) | DealerGroup;
  /**
   * Add only after you have seen the certificate.
   */
  accreditations?: (number | Accreditation)[] | null;
  /**
   * The end of their page's web address, for example smith-motors. Made from the dealership name when left empty.
   */
  slug: string;
  registrationNumber?: string | null;
  vatNumber?: string | null;
  /**
   * If they have one.
   */
  motorTradeNumber?: string | null;
  /**
   * Only Rynet staff see this.
   */
  verificationNotes?: string | null;
  /**
   * Sends them people selling a car on the site. Leave off unless they asked.
   */
  acceptsTradeIns?: boolean | null;
  /**
   * Leave empty to receive any make.
   */
  buysMakes?: (number | Make)[] | null;
  principal?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Buyers message this number from the site.
   */
  whatsappNumber?: string | null;
  plan?: (number | null) | Plan;
  /**
   * Not enforced yet.
   */
  listingLimit?: number | null;
  listingCount?: number | null;
  reviewScore?: number | null;
  reviewCount?: number | null;
  heroImages?: (number | Media)[] | null;
  franchises?: (number | Franchise)[] | null;
  socialProfiles?:
    | {
        platform?: ('facebook' | 'instagram' | 'youtube' | 'tiktok' | 'linkedin' | 'x') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * No enquiry emails are sent yet.
   */
  emailRouting?:
    | {
        leadType: 'enquiry' | 'test_drive' | 'finance' | 'trade_in' | 'callback';
        toAddress: string;
        branch?: (number | null) | Branch;
        id?: string | null;
      }[]
    | null;
  theme?: {
    /**
     * A colour code like #C81E2B, dark enough to read on white.
     */
    accent?: string | null;
    heroLayout?: ('standard' | 'split' | 'minimal') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Companies that own several dealerships.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-groups".
 */
export interface DealerGroup {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | DealerGroup;
  updatedAt: string;
  createdAt: string;
}
/**
 * Industry bodies such as the RMI, NADA and MIWA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accreditations".
 */
export interface Accreditation {
  id: number;
  name: string;
  badge?: (number | null) | Media;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Accreditation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  /**
   * Placeholder until real pricing is agreed.
   */
  monthlyPrice: number;
  /**
   * Not enforced yet.
   */
  listingLimit: number;
  branchLimit: number;
  userLimit: number;
  allowsMicrositeTheming?: boolean | null;
  allowsFeedImport?: boolean | null;
  summary?: string | null;
  includedFeatures?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * There is no public pricing page yet.
   */
  isPublic?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Lower case, no spaces, for example growth.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The brands a dealership can be an official dealer for.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises".
 */
export interface Franchise {
  id: number;
  name: string;
  make?: (number | null) | Make;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Franchise;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  dealer: number | Dealer;
  /**
   * Head office or main showroom.
   */
  isPrimary?: boolean | null;
  addressLine1: string;
  addressLine2?: string | null;
  suburb?: string | null;
  city: number | City;
  province: number | Province;
  postalCode?: string | null;
  /**
   * For example: opposite the Engen on the N1 side.
   */
  directionsNote?: string | null;
  /**
   * Only change this if the map pin is in the wrong place.
   */
  latitude?: number | null;
  longitude?: number | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  tradingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        opensAt?: string | null;
        closesAt?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add the days this branch keeps different hours.
   */
  holidayOverrides?:
    | {
        date: string;
        label?: string | null;
        opensAt?: string | null;
        closesAt?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  photos?: (number | Media)[] | null;
  /**
   * Filled in from the branch name.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  province: number | Province;
  /**
   * The middle of the town, for the distance filter.
   */
  latitude?: number | null;
  longitude?: number | null;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * The nine provinces, used by the location filter and the dealership list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: number;
  name: string;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Province;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  name: string;
  make: number | Make;
  bodyType?: (number | null) | BodyType;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Model;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-types".
 */
export interface BodyType {
  id: number;
  name: string;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | BodyType;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  name: string;
  /**
   * Web address names are shared by all models, so the same variant name cannot exist twice.
   */
  model: number | Model;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Variant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuel-types".
 */
export interface FuelType {
  id: number;
  name: string;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | FuelType;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transmissions".
 */
export interface Transmission {
  id: number;
  name: string;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Transmission;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivetrains".
 */
export interface Drivetrain {
  id: number;
  name: string;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Drivetrain;
  updatedAt: string;
  createdAt: string;
}
/**
 * The makers' colour names, grouped so Deep Sea Blue and Aegean Blue both filter under Blue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colours".
 */
export interface Colour {
  id: number;
  name: string;
  /**
   * Buyers filter by the group, for example Blue.
   */
  family:
    | 'white'
    | 'silver'
    | 'grey'
    | 'black'
    | 'blue'
    | 'red'
    | 'green'
    | 'beige'
    | 'brown'
    | 'gold'
    | 'orange'
    | 'yellow'
    | 'purple'
    | 'other';
  /**
   * A hex colour like #1F4E8C.
   */
  swatch?: string | null;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Colour;
  updatedAt: string;
  createdAt: string;
}
/**
 * The features a car can have. Buyers filter by these, so pick from here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  name: string;
  category: number | FeatureCategory;
  /**
   * Not used on the site yet.
   */
  isHighlight?: boolean | null;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | Feature;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories".
 */
export interface FeatureCategory {
  id: number;
  name: string;
  /**
   * For example bakkie for pickup. Helps search and the sell form.
   */
  aliases?: string[] | null;
  /**
   * Untick to hide it. Cars that use it keep it.
   */
  isActive?: boolean | null;
  /**
   * Lower numbers come first.
   */
  sortOrder?: number | null;
  /**
   * Filled in from the name.
   */
  slug: string;
  /**
   * Hides this from the sell form. Cars that use it are not moved.
   */
  mergedInto?: (number | null) | FeatureCategory;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone?: string | null;
  email?: string | null;
  message?: string | null;
  type:
    | 'enquiry'
    | 'test_drive'
    | 'finance'
    | 'trade_in'
    | 'callback'
    | 'whatsapp_click'
    | 'phone_reveal'
    | 'dealer_contact'
    | 'agency_enquiry';
  vehicle?: (number | null) | Vehicle;
  /**
   * Empty for Rynet Digital enquiries and for sellers, who go to several dealerships.
   */
  dealer?: (number | null) | Dealer;
  branch?: (number | null) | Branch;
  tradeIn?: {
    make?: string | null;
    model?: string | null;
    modelYear?: number | null;
    mileageKm?: number | null;
    transmission?: ('manual' | 'automatic') | null;
    condition?: ('excellent' | 'good' | 'fair' | 'poor') | null;
    serviceHistory?: ('full' | 'partial' | 'none') | null;
    /**
     * If a bank still owns the car, it cannot be sold until the loan is settled.
     */
    finance?: ('none' | 'outstanding' | 'unsure') | null;
    province?: (number | null) | Province;
    city?: string | null;
    notes?: string | null;
  };
  notes?:
    | {
        body: string;
        author?: (number | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Every dealership that received this seller's details.
   */
  disclosures?:
    | {
        dealer: number | Dealer;
        disclosedAt: string;
        withdrawnAt?: string | null;
        id?: string | null;
      }[]
    | null;
  disclosedTo?: (number | Dealer)[] | null;
  /**
   * The POPIA consent they gave.
   */
  consent?: (number | null) | ConsentRecord;
  source?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    referrer?: string | null;
    landingPage?: string | null;
    deviceType?: string | null;
  };
  status: 'new' | 'contacted' | 'qualified' | 'appointment_set' | 'sold' | 'lost';
  lostReason?: string | null;
  assignedTo?: (number | null) | User;
  firstResponseAt?: string | null;
  isDemonstration?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in: Rynet staff and dealership staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Decides what this person can see and change.
   */
  role:
    | 'platform_admin'
    | 'platform_editor'
    | 'agency_account_manager'
    | 'dealer_owner'
    | 'dealer_manager'
    | 'dealer_sales'
    | 'analyst';
  /**
   * Needed for dealership roles.
   */
  dealer?: (number | null) | Dealer;
  /**
   * For example 082 123 4567.
   */
  phone?: string | null;
  /**
   * Suspended stops this person signing in, and signs them out now.
   */
  status: 'active' | 'invited' | 'suspended';
  /**
   * Each person turns this on for their own account.
   */
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  twoFactorRecoveryCodes?:
    | {
        hash?: string | null;
        id?: string | null;
      }[]
    | null;
  twoFactorConfirmedAt?: string | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * A permanent record of what people agreed to. Nothing here can be changed or deleted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  purpose: 'enquiry' | 'marketing' | 'dealer_marketing' | 'alerts' | 'finance' | 'trade_in';
  subjectEmail?: string | null;
  subjectPhone?: string | null;
  grantedAt: string;
  withdrawnAt?: string | null;
  policyVersion: string;
  evidence?: string | null;
  /**
   * A scrambled code, not their internet address.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who signed up on the site to save cars and enquire. They can never list a car.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyers".
 */
export interface Buyer {
  id: number;
  name: string;
  phone?: string | null;
  province?: (number | null) | Province;
  city?: (number | null) | City;
  /**
   * Not sent yet.
   */
  alertFrequency: 'instant' | 'daily' | 'weekly' | 'off';
  /**
   * Proof is kept in Consent records.
   */
  marketingConsent?: boolean | null;
  /**
   * Suspended stops this person signing in, and signs them out now.
   */
  status: 'active' | 'suspended' | 'deletion_requested';
  deletionRequestedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'buyers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'dealers';
        value: number | Dealer;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'buyers';
        value: number | Buyer;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'makes';
        value: number | Make;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'body-types';
        value: number | BodyType;
      } | null)
    | ({
        relationTo: 'fuel-types';
        value: number | FuelType;
      } | null)
    | ({
        relationTo: 'transmissions';
        value: number | Transmission;
      } | null)
    | ({
        relationTo: 'drivetrains';
        value: number | Drivetrain;
      } | null)
    | ({
        relationTo: 'colours';
        value: number | Colour;
      } | null)
    | ({
        relationTo: 'feature-categories';
        value: number | FeatureCategory;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'provinces';
        value: number | Province;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'franchises';
        value: number | Franchise;
      } | null)
    | ({
        relationTo: 'dealer-groups';
        value: number | DealerGroup;
      } | null)
    | ({
        relationTo: 'accreditations';
        value: number | Accreditation;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'buyers';
        value: number | Buyer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'buyers';
        value: number | Buyer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  title?: T;
  condition?: T;
  make?: T;
  model?: T;
  variant?: T;
  derivative?: T;
  modelYear?: T;
  registrationYear?: T;
  mileageKm?: T;
  bodyType?: T;
  fuelType?: T;
  transmission?: T;
  drivetrain?: T;
  exteriorColour?: T;
  interiorColour?: T;
  features?: T;
  description?: T;
  engineCapacityCc?: T;
  cylinders?: T;
  powerKw?: T;
  torqueNm?: T;
  doors?: T;
  seats?: T;
  price?: T;
  priceType?: T;
  vatStatus?: T;
  previousPrice?: T;
  priceHistory?:
    | T
    | {
        price?: T;
        changedAt?: T;
        id?: T;
      };
  monthlyEstimate?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  video?:
    | T
    | {
        url?: T;
        provider?: T;
      };
  stockNumber?: T;
  vin?: T;
  serviceHistory?: T;
  roadworthy?: T;
  licenceExpiry?: T;
  warrantyRemaining?:
    | T
    | {
        months?: T;
        km?: T;
        provider?: T;
      };
  status?: T;
  dealer?: T;
  branch?: T;
  isDemonstration?: T;
  publicRef?: T;
  publishedAt?: T;
  soldAt?: T;
  viewCount?: T;
  leadCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  verificationStatus?: T;
  isDemonstration?: T;
  tradingName?: T;
  legalName?: T;
  logo?: T;
  aboutRichText?: T;
  foundedYear?: T;
  group?: T;
  accreditations?: T;
  slug?: T;
  registrationNumber?: T;
  vatNumber?: T;
  motorTradeNumber?: T;
  verificationNotes?: T;
  acceptsTradeIns?: T;
  buysMakes?: T;
  principal?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  whatsappNumber?: T;
  plan?: T;
  listingLimit?: T;
  listingCount?: T;
  reviewScore?: T;
  reviewCount?: T;
  heroImages?: T;
  franchises?: T;
  socialProfiles?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  emailRouting?:
    | T
    | {
        leadType?: T;
        toAddress?: T;
        branch?: T;
        id?: T;
      };
  theme?:
    | T
    | {
        accent?: T;
        heroLayout?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  type?: T;
  vehicle?: T;
  dealer?: T;
  branch?: T;
  tradeIn?:
    | T
    | {
        make?: T;
        model?: T;
        modelYear?: T;
        mileageKm?: T;
        transmission?: T;
        condition?: T;
        serviceHistory?: T;
        finance?: T;
        province?: T;
        city?: T;
        notes?: T;
      };
  notes?:
    | T
    | {
        body?: T;
        author?: T;
        createdAt?: T;
        id?: T;
      };
  disclosures?:
    | T
    | {
        dealer?: T;
        disclosedAt?: T;
        withdrawnAt?: T;
        id?: T;
      };
  disclosedTo?: T;
  consent?: T;
  source?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        referrer?: T;
        landingPage?: T;
        deviceType?: T;
      };
  status?: T;
  lostReason?: T;
  assignedTo?: T;
  firstResponseAt?: T;
  isDemonstration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  dealer?: T;
  isPrimary?: T;
  addressLine1?: T;
  addressLine2?: T;
  suburb?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  directionsNote?: T;
  latitude?: T;
  longitude?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  tradingHours?:
    | T
    | {
        day?: T;
        opensAt?: T;
        closesAt?: T;
        closed?: T;
        id?: T;
      };
  holidayOverrides?:
    | T
    | {
        date?: T;
        label?: T;
        opensAt?: T;
        closesAt?: T;
        closed?: T;
        id?: T;
      };
  photos?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isDecorative?: T;
  credit?: T;
  isDemonstration?: T;
  dealer?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  dealer?: T;
  phone?: T;
  status?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  twoFactorRecoveryCodes?:
    | T
    | {
        hash?: T;
        id?: T;
      };
  twoFactorConfirmedAt?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyers_select".
 */
export interface BuyersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  province?: T;
  city?: T;
  alertFrequency?: T;
  marketingConsent?: T;
  status?: T;
  deletionRequestedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  monthlyPrice?: T;
  listingLimit?: T;
  branchLimit?: T;
  userLimit?: T;
  allowsMicrositeTheming?: T;
  allowsFeedImport?: T;
  summary?: T;
  includedFeatures?:
    | T
    | {
        label?: T;
        id?: T;
      };
  isPublic?: T;
  sortOrder?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes_select".
 */
export interface MakesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  isPopular?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  name?: T;
  make?: T;
  bodyType?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  name?: T;
  model?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-types_select".
 */
export interface BodyTypesSelect<T extends boolean = true> {
  name?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuel-types_select".
 */
export interface FuelTypesSelect<T extends boolean = true> {
  name?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transmissions_select".
 */
export interface TransmissionsSelect<T extends boolean = true> {
  name?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivetrains_select".
 */
export interface DrivetrainsSelect<T extends boolean = true> {
  name?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colours_select".
 */
export interface ColoursSelect<T extends boolean = true> {
  name?: T;
  family?: T;
  swatch?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories_select".
 */
export interface FeatureCategoriesSelect<T extends boolean = true> {
  name?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  isHighlight?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  latitude?: T;
  longitude?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises_select".
 */
export interface FranchisesSelect<T extends boolean = true> {
  name?: T;
  make?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-groups_select".
 */
export interface DealerGroupsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accreditations_select".
 */
export interface AccreditationsSelect<T extends boolean = true> {
  name?: T;
  badge?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  slug?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  purpose?: T;
  subjectEmail?: T;
  subjectPhone?: T;
  grantedAt?: T;
  withdrawnAt?: T;
  policyVersion?: T;
  evidence?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The figures behind every monthly instalment shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-defaults".
 */
export interface FinanceDefault {
  id: number;
  /**
   * The Reserve Bank prime rate. Change it on the day it moves.
   */
  primeRatePercent: number;
  /**
   * Most buyers pay more than prime.
   */
  defaultRateOffsetPercent: number;
  defaultTermMonths: number;
  defaultDepositPercent: number;
  defaultBalloonPercent: number;
  /**
   * Including VAT.
   */
  initiationFee: number;
  /**
   * Including VAT.
   */
  monthlyServiceFee: number;
  /**
   * Required by law. Keep the review note until an attorney signs it off.
   */
  disclaimer: string;
  lastReviewedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-defaults_select".
 */
export interface FinanceDefaultsSelect<T extends boolean = true> {
  primeRatePercent?: T;
  defaultRateOffsetPercent?: T;
  defaultTermMonths?: T;
  defaultDepositPercent?: T;
  defaultBalloonPercent?: T;
  initiationFee?: T;
  monthlyServiceFee?: T;
  disclaimer?: T;
  lastReviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}