/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    buyers: BuyerAuthOperations;
  };
  blocks: {};
  collections: {
    vehicles: Vehicle;
    dealers: Dealer;
    branches: Branch;
    plans: Plan;
    leads: Lead;
    'consent-records': ConsentRecord;
    makes: Make;
    models: Model;
    variants: Variant;
    'body-types': BodyType;
    'fuel-types': FuelType;
    transmissions: Transmission;
    drivetrains: Drivetrain;
    colours: Colour;
    'feature-categories': FeatureCategory;
    features: Feature;
    provinces: Province;
    cities: City;
    franchises: Franchise;
    'dealer-groups': DealerGroup;
    accreditations: Accreditation;
    media: Media;
    users: User;
    buyers: Buyer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    makes: MakesSelect<false> | MakesSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    'body-types': BodyTypesSelect<false> | BodyTypesSelect<true>;
    'fuel-types': FuelTypesSelect<false> | FuelTypesSelect<true>;
    transmissions: TransmissionsSelect<false> | TransmissionsSelect<true>;
    drivetrains: DrivetrainsSelect<false> | DrivetrainsSelect<true>;
    colours: ColoursSelect<false> | ColoursSelect<true>;
    'feature-categories': FeatureCategoriesSelect<false> | FeatureCategoriesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    franchises: FranchisesSelect<false> | FranchisesSelect<true>;
    'dealer-groups': DealerGroupsSelect<false> | DealerGroupsSelect<true>;
    accreditations: AccreditationsSelect<false> | AccreditationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    buyers: BuyersSelect<false> | BuyersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'finance-defaults': FinanceDefault;
  };
  globalsSelect: {
    'finance-defaults': FinanceDefaultsSelect<false> | FinanceDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Buyer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface BuyerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  /**
   * Built from the year, make, model and variant. Not edited by hand.
   */
  title?: string | null;
  /**
   * The stable id in the URL. Not the database id, which would leak stock volume, and not the stock number, which dealers change.
   */
  publicRef?: string | null;
  /**
   * Set automatically from the signed-in user.
   */
  dealer: number | Dealer;
  /**
   * Which branch the vehicle physically sits at.
   */
  branch?: (number | null) | Branch;
  status: 'draft' | 'pending_review' | 'live' | 'reserved' | 'sold' | 'expired' | 'archived';
  condition: 'new' | 'demo' | 'pre_owned';
  make: number | Make;
  model: number | Model;
  variant?: (number | null) | Variant;
  /**
   * Anything the variant list does not cover, for example a trim pack.
   */
  derivative?: string | null;
  modelYear: number;
  registrationYear?: number | null;
  mileageKm: number;
  bodyType?: (number | null) | BodyType;
  fuelType?: (number | null) | FuelType;
  transmission?: (number | null) | Transmission;
  drivetrain?: (number | null) | Drivetrain;
  engineCapacityCc?: number | null;
  cylinders?: number | null;
  powerKw?: number | null;
  torqueNm?: number | null;
  exteriorColour?: (number | null) | Colour;
  interiorColour?: (number | null) | Colour;
  doors?: number | null;
  seats?: number | null;
  /**
   * Structured, never free text. A free-text feature cannot be filtered, compared or counted.
   */
  features?: (number | Feature)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  priceType: 'retail' | 'on_the_road' | 'poa';
  vatStatus?: ('vat_inclusive' | 'vat_exclusive' | 'non_vat') | null;
  /**
   * Set automatically when the price changes. Drives the price-drop badge.
   */
  previousPrice?: number | null;
  /**
   * Append only.
   */
  priceHistory?:
    | {
        price?: number | null;
        changedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Derived from the finance defaults, not entered. Recalculated for all stock when the prime rate changes.
   */
  monthlyEstimate?: number | null;
  /**
   * Stored encrypted, never returned to a public query and never published in structured data.
   */
  vin?: string | null;
  stockNumber?: string | null;
  serviceHistory?: ('full_franchise' | 'full_independent' | 'partial' | 'none' | 'unknown') | null;
  warrantyRemaining?: {
    months?: number | null;
    km?: number | null;
    provider?: string | null;
  };
  roadworthy?: ('current' | 'expired' | 'not_required' | 'unknown') | null;
  licenceExpiry?: string | null;
  /**
   * Drag to reorder, or use the move buttons. Both work, because a drag-only reorder fails WCAG 2.2 SC 2.5.7.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Left empty, this is generated from the vehicle's own details. Override it when the photo shows something specific.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  video?: {
    url?: string | null;
    provider?: ('youtube' | 'vimeo') | null;
  };
  publishedAt?: string | null;
  soldAt?: string | null;
  /**
   * Buffered in memory and flushed by cron. Never written on a page view: on SQLite that would be a write lock on the busiest page on the site.
   */
  viewCount?: number | null;
  leadCount?: number | null;
  /**
   * Seeded example stock. Labelled as such wherever it appears publicly.
   */
  isDemonstration?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: number;
  tradingName: string;
  /**
   * As registered with CIPC. May differ from the trading name.
   */
  legalName: string;
  /**
   * Their address at /dealers/[slug].
   */
  slug: string;
  logo?: (number | null) | Media;
  heroImages?: (number | Media)[] | null;
  aboutRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  foundedYear?: number | null;
  group?: (number | null) | DealerGroup;
  franchises?: (number | Franchise)[] | null;
  /**
   * Only add an accreditation once the certificate has been seen. This is a trust claim.
   */
  accreditations?: (number | Accreditation)[] | null;
  /**
   * Nothing publishes unless this reads Verified.
   */
  verificationStatus: 'pending' | 'verified' | 'suspended' | 'archived';
  /**
   * CIPC company registration number.
   */
  registrationNumber?: string | null;
  vatNumber?: string | null;
  /**
   * Motor trade number, where the dealership holds one.
   */
  motorTradeNumber?: string | null;
  /**
   * Internal. Never shown to the dealership or the public.
   */
  verificationNotes?: string | null;
  principal?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  whatsappNumber?: string | null;
  /**
   * Where each kind of lead goes. Without a rule, leads fall back to the dealer principal.
   */
  emailRouting?:
    | {
        leadType: 'enquiry' | 'test_drive' | 'finance' | 'trade_in' | 'callback';
        toAddress: string;
        branch?: (number | null) | Branch;
        id?: string | null;
      }[]
    | null;
  socialProfiles?:
    | {
        platform?: ('facebook' | 'instagram' | 'youtube' | 'tiktok' | 'linkedin' | 'x') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Available on higher plans. Colours are contrast-checked on save and rejected if they fail.
   */
  theme?: {
    /**
     * Hex value, for example #E32432. Must reach 4.5:1 against white or the microsite becomes unreadable for some visitors.
     */
    accent?: string | null;
    heroLayout?: ('standard' | 'split' | 'minimal') | null;
  };
  plan?: (number | null) | Plan;
  /**
   * Set from the plan. Overridable per dealership by staff.
   */
  listingLimit?: number | null;
  /**
   * Live listings. Maintained by a job, never written on a page view.
   */
  listingCount?: number | null;
  /**
   * Computed. Stays empty until the dealership has five verified reviews, and no aggregateRating is emitted before then.
   */
  reviewScore?: number | null;
  reviewCount?: number | null;
  /**
   * Seeded example dealership, not a real business. Labelled as such everywhere it appears on the public site.
   */
  isDemonstration?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every image needs alt text, or an explicit decorative flag. This is enforced.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for someone who cannot see it. Describe the subject, not the file, so "2023 Toyota Hilux Raider, front three-quarter" rather than "vehicle photo".
   */
  alt?: string | null;
  /**
   * Tick only for images that carry no information, such as a background texture. These are hidden from screen readers.
   */
  isDecorative?: boolean | null;
  /**
   * Photographer or source, where one is owed.
   */
  credit?: string | null;
  /**
   * Groups the library. For example: stock, dealers, editorial, agency.
   */
  folder?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-groups".
 */
export interface DealerGroup {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | DealerGroup;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manufacturer franchise affiliations a dealership holds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises".
 */
export interface Franchise {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Franchise;
  make?: (number | null) | Make;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manufacturers. The slug appears directly under /cars/, so reserved route words are rejected.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes".
 */
export interface Make {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Make;
  logo?: (number | null) | Media;
  /**
   * Shown in the shortlist above the full A to Z list on the search page.
   */
  isPopular?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Industry bodies such as the RMI, NADA and MIWA. Shown on a dealer profile only once verified.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accreditations".
 */
export interface Accreditation {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Accreditation;
  badge?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  slug: string;
  dealer: number | Dealer;
  /**
   * The head office or main showroom.
   */
  isPrimary?: boolean | null;
  addressLine1: string;
  addressLine2?: string | null;
  suburb?: string | null;
  city: number | City;
  province: number | Province;
  postalCode?: string | null;
  /**
   * Geocoded on save. Override only when the pin lands wrong.
   */
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Plain directions, for example "opposite the Engen on the N1 side".
   */
  directionsNote?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  /**
   * Shown on the branch page and marked up as openingHoursSpecification.
   */
  tradingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        closed?: boolean | null;
        opensAt?: string | null;
        closesAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * South Africa has twelve public holidays and dealerships keep different hours on them. Without these the site tells buyers a branch is open when it is shut.
   */
  holidayOverrides?:
    | {
        date: string;
        label?: string | null;
        closed?: boolean | null;
        opensAt?: string | null;
        closesAt?: string | null;
        id?: string | null;
      }[]
    | null;
  photos?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | City;
  province: number | Province;
  /**
   * Centre point, used to seed the radius filter when a buyer picks a city.
   */
  latitude?: number | null;
  longitude?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The nine provinces. Used by the location facet and the dealer directory.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Province;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  slug: string;
  /**
   * Rand per month, excluding VAT. PLACEHOLDER until real pricing is supplied. See docs/CONTENT-NEEDED.md.
   */
  monthlyPrice: number;
  listingLimit: number;
  branchLimit: number;
  userLimit: number;
  /**
   * Lets the dealership set their own accent colour and hero layout.
   */
  allowsMicrositeTheming?: boolean | null;
  /**
   * Scheduled stock feed syndication rather than manual capture only.
   */
  allowsFeedImport?: boolean | null;
  summary?: string | null;
  includedFeatures?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the public pricing page. Leave off while the price is a placeholder.
   */
  isPublic?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Model;
  make: number | Make;
  /**
   * The usual body for this model. A listing can still override it.
   */
  bodyType?: (number | null) | BodyType;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-types".
 */
export interface BodyType {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | BodyType;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Variant;
  model: number | Model;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuel-types".
 */
export interface FuelType {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | FuelType;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transmissions".
 */
export interface Transmission {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Transmission;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivetrains".
 */
export interface Drivetrain {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Drivetrain;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manufacturer colour names, grouped into families so "Deep Sea Blue" and "Aegean Blue" both filter under Blue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colours".
 */
export interface Colour {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Colour;
  family:
    | 'white'
    | 'silver'
    | 'grey'
    | 'black'
    | 'blue'
    | 'red'
    | 'green'
    | 'beige'
    | 'brown'
    | 'gold'
    | 'orange'
    | 'yellow'
    | 'purple'
    | 'other';
  /**
   * Hex value for the filter swatch. Decorative only, never the sole indicator.
   */
  swatch?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * A structured list, never free text. Free-text features cannot be filtered, compared or counted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | Feature;
  category: number | FeatureCategory;
  /**
   * Shown as a chip on the listing card, not just in the full spec.
   */
  isHighlight?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories".
 */
export interface FeatureCategory {
  id: number;
  name: string;
  /**
   * Appears in the URL. Changing it writes a redirect automatically.
   */
  slug: string;
  /**
   * Other names buyers and dealer feeds use for this. Feeds the search box and the stock importer. For example a bakkie is a pickup, a combi is an MPV.
   */
  aliases?: string[] | null;
  /**
   * Inactive values stay on existing listings but stop appearing in filters.
   */
  isActive?: boolean | null;
  /**
   * Lower sorts first. Equal values fall back to alphabetical.
   */
  sortOrder?: number | null;
  /**
   * Set when this is a duplicate. References are rewritten to the target and a redirect is written. Merge rather than delete, or every listing pointing here loses its value.
   */
  mergedInto?: (number | null) | FeatureCategory;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type:
    | 'enquiry'
    | 'test_drive'
    | 'finance'
    | 'trade_in'
    | 'callback'
    | 'whatsapp_click'
    | 'phone_reveal'
    | 'dealer_contact'
    | 'agency_enquiry';
  vehicle?: (number | null) | Vehicle;
  dealer?: (number | null) | Dealer;
  branch?: (number | null) | Branch;
  name: string;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  status: 'new' | 'contacted' | 'qualified' | 'appointment_set' | 'sold' | 'lost';
  lostReason?: string | null;
  assignedTo?: (number | null) | User;
  /**
   * Stamped on the first outbound action. Drives the response SLA timer.
   */
  firstResponseAt?: string | null;
  /**
   * Captured at submission. Read only afterwards.
   */
  source?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    referrer?: string | null;
    landingPage?: string | null;
    deviceType?: string | null;
  };
  /**
   * POPIA lawful basis. A lead without a consent record is a lead we cannot lawfully act on.
   */
  consent?: (number | null) | ConsentRecord;
  notes?:
    | {
        body: string;
        author?: (number | null) | User;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  isDemonstration?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role:
    | 'platform_admin'
    | 'platform_editor'
    | 'agency_account_manager'
    | 'dealer_owner'
    | 'dealer_manager'
    | 'dealer_sales'
    | 'analyst';
  /**
   * Required for every dealer role. Set automatically for dealer users.
   */
  dealer?: (number | null) | Dealer;
  /**
   * South African format, for example 012 345 6789 or +27 12 345 6789.
   */
  phone?: string | null;
  status: 'active' | 'invited' | 'suspended';
  /**
   * Mandatory for platform admins and dealer principals. Enforced at sign-in, not here.
   */
  twoFactorEnabled?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Append only. Nothing here can be edited or deleted, which is the point.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  purpose: 'enquiry' | 'marketing' | 'dealer_marketing' | 'alerts' | 'finance';
  subjectEmail?: string | null;
  subjectPhone?: string | null;
  /**
   * Which version of the privacy notice was on screen when this was given.
   */
  policyVersion: string;
  grantedAt: string;
  /**
   * Set by writing a new withdrawal record, not by editing this one. Shown here for readability.
   */
  withdrawnAt?: string | null;
  /**
   * The exact wording the person agreed to, stored verbatim. Not a reference to it, the text itself, because the wording on the page will change.
   */
  evidence?: string | null;
  /**
   * Hashed, never the raw address. Enough to demonstrate a distinct submission, not enough to be personal information in its own right.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Consumer accounts. These can save and enquire. They can never list a vehicle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyers".
 */
export interface Buyer {
  id: number;
  name: string;
  phone?: string | null;
  province?: (number | null) | Province;
  city?: (number | null) | City;
  alertFrequency: 'instant' | 'daily' | 'weekly' | 'off';
  /**
   * Opt in only, never pre-ticked. The evidence lives in consent-records with a timestamp and the policy version.
   */
  marketingConsent?: boolean | null;
  status: 'active' | 'suspended' | 'deletion_requested';
  /**
   * POPIA section 24. The purge job acts on this, and the deletion actually removes the data.
   */
  deletionRequestedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'buyers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'dealers';
        value: number | Dealer;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null)
    | ({
        relationTo: 'makes';
        value: number | Make;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'body-types';
        value: number | BodyType;
      } | null)
    | ({
        relationTo: 'fuel-types';
        value: number | FuelType;
      } | null)
    | ({
        relationTo: 'transmissions';
        value: number | Transmission;
      } | null)
    | ({
        relationTo: 'drivetrains';
        value: number | Drivetrain;
      } | null)
    | ({
        relationTo: 'colours';
        value: number | Colour;
      } | null)
    | ({
        relationTo: 'feature-categories';
        value: number | FeatureCategory;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'provinces';
        value: number | Province;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'franchises';
        value: number | Franchise;
      } | null)
    | ({
        relationTo: 'dealer-groups';
        value: number | DealerGroup;
      } | null)
    | ({
        relationTo: 'accreditations';
        value: number | Accreditation;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'buyers';
        value: number | Buyer;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'buyers';
        value: number | Buyer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'buyers';
        value: number | Buyer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  title?: T;
  publicRef?: T;
  dealer?: T;
  branch?: T;
  status?: T;
  condition?: T;
  make?: T;
  model?: T;
  variant?: T;
  derivative?: T;
  modelYear?: T;
  registrationYear?: T;
  mileageKm?: T;
  bodyType?: T;
  fuelType?: T;
  transmission?: T;
  drivetrain?: T;
  engineCapacityCc?: T;
  cylinders?: T;
  powerKw?: T;
  torqueNm?: T;
  exteriorColour?: T;
  interiorColour?: T;
  doors?: T;
  seats?: T;
  features?: T;
  description?: T;
  price?: T;
  priceType?: T;
  vatStatus?: T;
  previousPrice?: T;
  priceHistory?:
    | T
    | {
        price?: T;
        changedAt?: T;
        id?: T;
      };
  monthlyEstimate?: T;
  vin?: T;
  stockNumber?: T;
  serviceHistory?: T;
  warrantyRemaining?:
    | T
    | {
        months?: T;
        km?: T;
        provider?: T;
      };
  roadworthy?: T;
  licenceExpiry?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  video?:
    | T
    | {
        url?: T;
        provider?: T;
      };
  publishedAt?: T;
  soldAt?: T;
  viewCount?: T;
  leadCount?: T;
  isDemonstration?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  tradingName?: T;
  legalName?: T;
  slug?: T;
  logo?: T;
  heroImages?: T;
  aboutRichText?: T;
  foundedYear?: T;
  group?: T;
  franchises?: T;
  accreditations?: T;
  verificationStatus?: T;
  registrationNumber?: T;
  vatNumber?: T;
  motorTradeNumber?: T;
  verificationNotes?: T;
  principal?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  whatsappNumber?: T;
  emailRouting?:
    | T
    | {
        leadType?: T;
        toAddress?: T;
        branch?: T;
        id?: T;
      };
  socialProfiles?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  theme?:
    | T
    | {
        accent?: T;
        heroLayout?: T;
      };
  plan?: T;
  listingLimit?: T;
  listingCount?: T;
  reviewScore?: T;
  reviewCount?: T;
  isDemonstration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  dealer?: T;
  isPrimary?: T;
  addressLine1?: T;
  addressLine2?: T;
  suburb?: T;
  city?: T;
  province?: T;
  postalCode?: T;
  latitude?: T;
  longitude?: T;
  directionsNote?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  tradingHours?:
    | T
    | {
        day?: T;
        closed?: T;
        opensAt?: T;
        closesAt?: T;
        id?: T;
      };
  holidayOverrides?:
    | T
    | {
        date?: T;
        label?: T;
        closed?: T;
        opensAt?: T;
        closesAt?: T;
        id?: T;
      };
  photos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  monthlyPrice?: T;
  listingLimit?: T;
  branchLimit?: T;
  userLimit?: T;
  allowsMicrositeTheming?: T;
  allowsFeedImport?: T;
  summary?: T;
  includedFeatures?:
    | T
    | {
        label?: T;
        id?: T;
      };
  isPublic?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  vehicle?: T;
  dealer?: T;
  branch?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  lostReason?: T;
  assignedTo?: T;
  firstResponseAt?: T;
  source?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        referrer?: T;
        landingPage?: T;
        deviceType?: T;
      };
  consent?: T;
  notes?:
    | T
    | {
        body?: T;
        author?: T;
        createdAt?: T;
        id?: T;
      };
  isDemonstration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  purpose?: T;
  subjectEmail?: T;
  subjectPhone?: T;
  policyVersion?: T;
  grantedAt?: T;
  withdrawnAt?: T;
  evidence?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makes_select".
 */
export interface MakesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  logo?: T;
  isPopular?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  make?: T;
  bodyType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "body-types_select".
 */
export interface BodyTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fuel-types_select".
 */
export interface FuelTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transmissions_select".
 */
export interface TransmissionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drivetrains_select".
 */
export interface DrivetrainsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colours_select".
 */
export interface ColoursSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  family?: T;
  swatch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-categories_select".
 */
export interface FeatureCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  category?: T;
  isHighlight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  province?: T;
  latitude?: T;
  longitude?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franchises_select".
 */
export interface FranchisesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  make?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealer-groups_select".
 */
export interface DealerGroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accreditations_select".
 */
export interface AccreditationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?: T;
  isActive?: T;
  sortOrder?: T;
  mergedInto?: T;
  badge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isDecorative?: T;
  credit?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  dealer?: T;
  phone?: T;
  status?: T;
  twoFactorEnabled?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyers_select".
 */
export interface BuyersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  province?: T;
  city?: T;
  alertFrequency?: T;
  marketingConsent?: T;
  status?: T;
  deletionRequestedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Drives every instalment estimate on the site. Changing the prime rate recalculates all stock.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-defaults".
 */
export interface FinanceDefault {
  id: number;
  /**
   * SARB prime. 10.5 as at 28 May 2026, on a 7.00 repo. Update this the day it moves.
   */
  primeRatePercent: number;
  /**
   * Added to prime for the default estimate, since few buyers get prime.
   */
  defaultRateOffsetPercent: number;
  defaultTermMonths: number;
  defaultDepositPercent: number;
  defaultBalloonPercent: number;
  /**
   * Rand, VAT inclusive. Capped by the NCA.
   */
  initiationFee: number;
  /**
   * Rand per month, VAT inclusive.
   */
  monthlyServiceFee: number;
  /**
   * Shown with every instalment figure on the site. Cannot be emptied. Keep the review marker until a South African attorney has signed this off.
   */
  disclaimer: string;
  /**
   * When the disclaimer wording was last checked by someone qualified.
   */
  lastReviewedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finance-defaults_select".
 */
export interface FinanceDefaultsSelect<T extends boolean = true> {
  primeRatePercent?: T;
  defaultRateOffsetPercent?: T;
  defaultTermMonths?: T;
  defaultDepositPercent?: T;
  defaultBalloonPercent?: T;
  initiationFee?: T;
  monthlyServiceFee?: T;
  disclaimer?: T;
  lastReviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}